# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awarded', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rated_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='techused',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Techused',
        ),
    ]
